1 page for viewing images
philipperker/capstone-project pull request #2
Opened 2022-05-06 11:04 UTC by philipperker

Hello,
with this pull request I have:
- created a page for view images
- created a component card with horizontal scrolling
- created fake NFT metadata
- fetch the fake metadata from  https://capstone-test-fft007am3-philipperker.vercel.app/
- deployed the branch 1-page-for-viewing-images for UI/UX tests  https://1-page-for-viewing-images-test-060522.vercel.app/

2022-05-06 13:22 UTC, PReichetanz reviewed
Looks good to me, found some issues to consider. Please make sure Prettier is working correctly.

2022-05-06 13:22 UTC, PReichetanz commented on client/src/App.test.js
> +it('renders App.js', () => {
We normally don't test the App.js as part of component testing, because this would rather be an integration test.
Besides, your test better fits to the NFTview.js since the main belongs there.

2022-05-06 13:22 UTC, PReichetanz commented on client/src/components/CardSlide/CardSlide.js
> +//https://capstone-test-42gsjahq5-philipperker.vercel.app/
```suggestion
```

2022-05-06 13:22 UTC, PReichetanz commented on client/src/components/CardSlide/CardSlide.js
> +
Please make sure Prettier is working correctly.

2022-05-06 13:22 UTC, PReichetanz commented on client/src/components/CardSlide/CardSlide.spec.js
> +
```suggestion
```

2022-05-06 13:22 UTC, PReichetanz commented on client/src/components/CardSlide/CardSlide.stories.js
> +
```suggestion
```

2022-05-06 13:22 UTC, PReichetanz commented on client/src/pages/NFTview.js
> +}
Prettier does not work here correctly.

2022-05-06 13:22 UTC, PReichetanz commented on client/src/pages/NFTview.spec.js
> +it('renders App.js', () => {
```suggestion
it('renders NFTview page', () => {
```

2022-05-06 13:22 UTC, PReichetanz commented on client/src/pages/NFTview.spec.js
> +
I think you should adjust the `it` statement and put them all together in one test.

2022-05-06 13:22 UTC, PReichetanz commented on client/src/pages/NFTview.spec.js
> +
I would consider adding the `describe` keyword here as well.

2022-05-06 13:51 UTC, mpagels requested changes
Hey Philipp,
good start here. But your tests need working. You have to test if something specific rendered in the DOM.

I have noticed that your `prettier` seems not to be working. Pls check that. 

The deployed backend on vercel is super nice. Bravo!

Pls review my review. If you have any questions pls aks!

2022-05-06 13:51 UTC, mpagels commented on client/src/App.test.js
> +  expect(mainElement).toBeInTheDocument();
This test just checks if a `main` element is in the `DOM`. But for the user it is not important if the `main` is here. You have to start thinking as a user, that using the Apop, when writing tests. When using the App, what should the user see? That is what you have to test. Is the content rendered.

2022-05-06 13:51 UTC, mpagels commented on client/src/components/CardSlide/CardSlide.js
> +//https://capstone-test-42gsjahq5-philipperker.vercel.app/
Comments here. You don't want comments in your production code.

2022-05-06 13:51 UTC, mpagels commented on client/src/components/CardSlide/CardSlide.js
> +          `https://capstone-test-fft007am3-philipperker.vercel.app/`
Super nice having the backend working on a vercel deployment.

2022-05-06 13:51 UTC, mpagels commented on client/src/components/CardSlide/CardSlide.spec.js
> +it('renders App.js', () => {
Is it? ;-) The string here helps you quickly see, which test was failing or going through. Seeing `renders App.js` but renders `CardSlide` is very confusing.

2022-05-06 13:51 UTC, mpagels commented on client/src/components/CardSlide/CardSlide.spec.js
> +  const mainElement = screen.getByTestId("collectionCardSlide_id_1")
This is always true. I would rather check if the content inside `ContainerCardSlide` is rendered correctly.

2022-05-06 13:51 UTC, mpagels commented on client/src/pages/NFTview.js
> +           <CardSlide />
Just a question, why are you calling here the same thing three times?

2022-05-06 13:51 UTC, mpagels commented on client/src/pages/NFTview.spec.js
> +  });
please find better test describtions. `"renders App.js"` is misleading here and when the test is running.

2022-05-06 13:51 UTC, mpagels commented on client/src/pages/NFTview.spec.js
> +    const collectionName1 = screen.getByTestId("collectionName_id_1")
This test just checks for the element with `collectionName_id_1` but not if the collections are rendered.

2022-05-06 13:51 UTC, mpagels commented on client/src/components/CardSlide/CardSlide.js
> +  const [error, setError] = useState(null);
You're not using the `error` information in your code. Do you need the state here?

2022-05-06 13:51 UTC, mpagels commented on client/src/components/CardSlide/CardSlide.js
> +        </ContainerCardSlide>
Semantically speaking, it would be better to work with a `list` here.

```
<ul>
    <li>...</li>
    <li>...</li>
</ul>
```` 
instead of `div`s

2022-05-09 17:46 UTC, philipperker commented on client/src/components/CardSlide/CardSlide.js
> +  const [error, setError] = useState(null);
Not yet in this user story. but in a later one ;)

2022-05-09 17:47 UTC, philipperker commented on client/src/pages/NFTview.js
> +           <CardSlide />
So that the screen fills up :D no, I need it later for the NFT evaluation. New NFT should be displayed in the first line, evaluated NFT in the middle and below.

2022-05-09 17:48 UTC, philipperker commented on client/src/components/CardSlide/CardSlide.js
> +        </ContainerCardSlide>
Thanks for the hint. I've already changed it

2022-05-09 17:49 UTC, merged